// Code generated by SQLBoiler 4.8.6 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package orm

var TableNames = struct {
	Order     string
	OrderItem string
	Product   string
}{
	Order:     "order",
	OrderItem: "order_item",
	Product:   "product",
}
